#!/bin/bash
set -euo pipefail

export LC_CTYPE=C LANG=C

# ==============================================================================
# CAWL Conversion Script for SAP Commerce Cloud (Hybris)
# ==============================================================================
# This script converts the Worldline GoPay payment plugin codebase into the
# CAWL-branded variant. It renames packages, directories, files, and performs
# text replacements so there is ZERO mention of "Worldline" or the "GoPay"
# product brand in the output.
#
# Usage:
#   ./cawl.sh [source_dir] [dest_dir]
#
# Defaults:
#   source_dir = ./hybris/bin/custom/worldline
#   dest_dir   = ./cawl_output
#
# SDK Replacement (optional - configure in cawl.conf alongside this script):
#   CAWL_SDK_GROUP_ID='com.cawl-solutions'
#   CAWL_SDK_ARTIFACT_ID='cawl-payments-sdk-java'
#   CAWL_SDK_VERSION='1.0.0'
#   CAWL_SDK_JAR='/path/to/jar'   # optional: uses Maven download if omitted
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

SRC_DIR="${1:-./hybris/bin/custom/worldline}"
DEST_DIR="${2:-./cawl_output}"

# ------------------------------------------------------------------------------
# Load configuration from cawl.conf
# ------------------------------------------------------------------------------
CAWL_CONF="${SCRIPT_DIR}/cawl.conf"
CAWL_SDK_GROUP_ID=
CAWL_SDK_ARTIFACT_ID=
CAWL_SDK_VERSION=
CAWL_SDK_JAR=

if [[ -f "$CAWL_CONF" ]]; then
    echo "Loading config from $CAWL_CONF"
    # shellcheck source=cawl.conf
    source "$CAWL_CONF"
else
    echo "WARNING: Config file not found at $CAWL_CONF - using defaults."
fi

# Auto-detect SDK jar from scripts/sdk/ directory if CAWL_SDK_JAR is not set
if [[ -z "$CAWL_SDK_JAR" ]]; then
    SDK_DIR="$SCRIPT_DIR/sdk"
    if [[ -d "$SDK_DIR" ]]; then
        AUTO_JAR=$(find "$SDK_DIR" -maxdepth 1 -name "*.jar" -type f | head -1)
        if [[ -n "$AUTO_JAR" ]]; then
            CAWL_SDK_JAR="$AUTO_JAR"
            echo "Auto-detected SDK jar: $CAWL_SDK_JAR"
        fi
    fi
fi

if [[ ! -d "$SRC_DIR" ]]; then
    echo "ERROR: Source directory '$SRC_DIR' does not exist."
    exit 1
fi

# Detect the SDK version the source plugin ships with. Used as the default
# when cawl.conf does not pin CAWL_SDK_VERSION, so the CAWL output always
# carries the same SDK as the Worldline release it was generated from.
SRC_DEPS_XML="$SRC_DIR/worldlinegopaycore/external-dependencies.xml"
SRC_SDK_VERSION=""
if [[ -f "$SRC_DEPS_XML" ]]; then
    SRC_SDK_VERSION=$(sed -n 's|.*<worldline\.gopay\.version>\([^<]*\)</worldline\.gopay\.version>.*|\1|p' "$SRC_DEPS_XML" | head -1)
fi
if [[ -z "$CAWL_SDK_VERSION" && -n "$SRC_SDK_VERSION" ]]; then
    CAWL_SDK_VERSION="$SRC_SDK_VERSION"
    echo "Using SDK version from source plugin: $CAWL_SDK_VERSION"
elif [[ -n "$SRC_SDK_VERSION" && "$CAWL_SDK_VERSION" != "$SRC_SDK_VERSION" ]]; then
    echo "WARNING: cawl.conf pins SDK $CAWL_SDK_VERSION but the source plugin ships $SRC_SDK_VERSION."
fi

# ------------------------------------------------------------------------------
# 1. Prepare target directory
# ------------------------------------------------------------------------------
echo "=== Step 1: Preparing output directory ==="
rm -rf "$DEST_DIR"
rsync -a --exclude='node_modules' --exclude='.git' --exclude='documentation' "$SRC_DIR"/ "$DEST_DIR"/

cd "$DEST_DIR" || { echo "Failed to enter $DEST_DIR"; exit 1; }

# Remove stale compiled artifacts - they contain bytecode referencing the old
# package names and must be regenerated by ant clean all
find . -name "*.class" -type f -delete
find . -type d -name "gensrc" -exec rm -rf {} + 2>/dev/null || true
echo "  Removed stale .class and gensrc/ files."

# ------------------------------------------------------------------------------
# 2. Define text replacements (ORDER MATTERS - most specific first)
# ------------------------------------------------------------------------------
# IMPORTANT: Longer/more-specific patterns MUST come before shorter ones so that
# sed processes them first and avoids partial matches.
#
# Pattern ordering rationale:
#   1. "Worldline GoPay" before everything (the product brand, contains
#      "Worldline" - if the generic pass ran first it would leave "CAWL GoPay")
#   2. "worldlinegopay" before "worldline" (extension names)
#   3. "Worldlinegopay" before "Worldline" (Constants class prefixes)
#   4. "WORLDLINE_DIRECT" / "WORLDLINE" (uppercase constants & enum values)
#   5. "worldline" / "Worldline" (everything else)
#   6. "GoPay" / "gopay" AFTER the generic pass - these are the product-brand
#      remnants left inside identifiers such as the package com.worldline.gopay
#      and the type WorldlineGoPayCheckoutFacade. They map to Direct/direct so
#      that the CAWL output keeps its established com.cawl.direct package and
#      cawl.direct.* property keys.
#   7. Brand-specific strings (emails, labels)
# ------------------------------------------------------------------------------

declare -a PATTERNS=(
    # --- Product brand (MUST be first: it contains "Worldline") ---
    "Worldline GoPay"

    # --- Extension / compound names (most specific first) ---
    "worldlinegopay"
    "Worldlinegopay"
    "WORLDLINE_DIRECT"

    # --- All-caps (enum values, constants like WORLDLINE_WAITING_AUTH) ---
    "WORLDLINE"

    # --- CamelCase variant "WorldLine" (capital L) ---
    "WorldLine"
    "worldLine"

    # --- Generic lowercase & PascalCase ---
    "worldline"
    "Worldline"

    # --- Product-brand remnants inside identifiers (must come AFTER the
    #     generic patterns, otherwise "Worldline GoPay" would be split) ---
    "GoPay"
    "GOPAY"
    "gopay"

    # --- Email addresses (must come after generic patterns to override) ---
    # These are applied in the sed script AFTER the generic patterns, so the
    # generic pass will have already changed them. We fix them here.
    "isvpartners@cawl\\.com"
    "support\\.ecom@cawl\\.com"
)

declare -a REPLACEMENTS=(
    # --- Product brand ---
    "CAWL"

    # --- Extension / compound names ---
    "cawl"
    "Cawl"
    "CAWL"

    # --- All-caps ---
    "CAWL"

    # --- CamelCase variant "WorldLine" (capital L) ---
    "CAWL"
    "cawl"

    # --- Generic lowercase & PascalCase ---
    "cawl"
    "CAWL"

    # --- Product-brand remnants inside identifiers ---
    "Direct"
    "DIRECT"
    "direct"

    # --- Email addresses (restore to CAWL-branded emails) ---
    "isvpartners@cawl.com"
    "support.ecom@cawl.com"
)

# ------------------------------------------------------------------------------
# 3. Portable `sed -i` detection
# ------------------------------------------------------------------------------
if sed --version >/dev/null 2>&1; then
    SED_INPLACE=(-i)          # GNU sed
else
    SED_INPLACE=(-i '')       # BSD/macOS sed
fi

# ------------------------------------------------------------------------------
# 4. Rename directories and files, build sed script
# ------------------------------------------------------------------------------
sed_script=$(mktemp)
trap 'rm -f "$sed_script"' EXIT

# Build the combined sed script
for i in "${!PATTERNS[@]}"; do
    printf 's/%s/%s/g\n' "${PATTERNS[$i]}" "${REPLACEMENTS[$i]}" >> "$sed_script"
done

echo ""
echo "=== Step 2: Renaming directories ==="

# Rename directories - process deepest paths first to avoid breaking parent paths
# We iterate the patterns in order (most specific first)
for i in "${!PATTERNS[@]}"; do
    pattern="${PATTERNS[$i]}"
    replacement="${REPLACEMENTS[$i]}"

    # Skip regex-only patterns (those with backslashes) - they don't match dir names
    [[ "$pattern" == *\\* ]] && continue

    # Rename directories (deepest first via -depth)
    # Only rename the LAST path component to avoid breaking parent paths
    find . -depth -type d -name "*${pattern}*" 2>/dev/null | while IFS= read -r dir; do
        parent="$(dirname "$dir")"
        base="$(basename "$dir")"
        newbase="$(echo "$base" | sed -e "s/${pattern}/${replacement}/g")"
        if [[ "$base" != "$newbase" ]]; then
            echo "  DIR: $dir -> $parent/$newbase"
            mv "$dir" "$parent/$newbase"
        fi
    done
done

echo ""
echo "=== Step 3: Renaming files ==="

for i in "${!PATTERNS[@]}"; do
    pattern="${PATTERNS[$i]}"
    replacement="${REPLACEMENTS[$i]}"

    # Skip regex-only patterns
    [[ "$pattern" == *\\* ]] && continue

    find . -type f -name "*${pattern}*" 2>/dev/null | while IFS= read -r file; do
        parent="$(dirname "$file")"
        base="$(basename "$file")"
        newbase="$(echo "$base" | sed -e "s/${pattern}/${replacement}/g")"
        if [[ "$base" != "$newbase" ]]; then
            echo "  FILE: $file -> $parent/$newbase"
            mv "$file" "$parent/$newbase"
        fi
    done
done

# ------------------------------------------------------------------------------
# 5. Rename Java package directories
# ------------------------------------------------------------------------------
# The Java package com.worldline.gopay lives under:
#   src/com/worldline/gopay/
#   testsrc/com/worldline/gopay/
#   web/src/com/worldline/gopay/
#   backoffice/src/com/worldline/gopay/
#
# After step 4 the "worldline" dirs are renamed to "cawl" and the "gopay" dirs
# to "direct", so the directory structure should already be com/cawl/direct/.
# Verify and report.

echo ""
echo "=== Step 4: Verifying package directory structure ==="

remaining_worldline_dirs=$(find . -type d \( -name "*worldline*" -o -name "*gopay*" -o -name "*GoPay*" \) 2>/dev/null || true)
if [[ -n "$remaining_worldline_dirs" ]]; then
    echo "  WARNING: Found remaining directories with 'worldline' or 'gopay':"
    echo "$remaining_worldline_dirs" | while IFS= read -r d; do echo "    $d"; done
else
    echo "  OK: No directories containing 'worldline' or 'gopay' remain."
fi

# ------------------------------------------------------------------------------
# 6. Apply text replacements to all files
# ------------------------------------------------------------------------------
echo ""
echo "=== Step 5: Applying text replacements ==="

# Apply to text files only (skip binary files like .jar, .class, images)
find . -type f \
    ! -name "*.jar" \
    ! -name "*.class" \
    ! -name "*.png" \
    ! -name "*.gif" \
    ! -name "*.jpg" \
    ! -name "*.jpeg" \
    ! -name "*.ico" \
    ! -name "*.woff" \
    ! -name "*.woff2" \
    ! -name "*.ttf" \
    ! -name "*.eot" \
    ! -name "*.svg" \
    ! -name "*.zip" \
    ! -name "*.gz" \
    ! -name "*.war" \
    -exec sed "${SED_INPLACE[@]}" -f "$sed_script" {} +

echo "  Text replacements applied."

# ------------------------------------------------------------------------------
# 6b. Fix CAWL acronym casing globally
# ------------------------------------------------------------------------------
# The generic replacement turns "worldlineXxx" -> "cawlXxx" (lowercase) but
# "WorldlineXxx" -> "CAWLXxx" (uppercase) in Java. This creates mismatches
# across ALL file types:
#
#   - items.xml qualifier="cawlXxx" generates getCawlXxx(), not getCAWLXxx()
#   - beans.xml property name generates getCawlXxx(), not getCAWLXxx()
#   - Spring XML bean names conflict with @Controller scan names
#   - Spring XML property names don't match Java setters
#   - JSP EL ${order.cawlPaymentInfo} doesn't match getCAWLPaymentInfo()
#   - ImpEx attribute qualifiers don't match items.xml
#
# Two-pass fix:
#   1. Config/template files: fix ALL occurrences of cawl[A-Z] -> CAWL[A-Z]
#   2. Java files: fix ONLY inside quoted strings ("cawl[A-Z] -> "CAWL[A-Z])
#      to handle @Resource(name="cawlXxx"), @Component("cawlXxx"), etc.
#      Variable/field names (unquoted) must stay lowercase to avoid colliding
#      with class names (e.g. cawlRecurringType vs CAWLRecurringType).
echo ""
echo "=== Step 5b: Fixing CAWL acronym casing ==="

# Pass 1: all non-Java text files - fix everywhere
find . -type f \
    ! -name "*.java" \
    ! -name "*.jar" \
    ! -name "*.class" \
    ! -name "*.png" \
    ! -name "*.gif" \
    ! -name "*.jpg" \
    ! -name "*.jpeg" \
    ! -name "*.ico" \
    ! -name "*.woff" \
    ! -name "*.woff2" \
    ! -name "*.ttf" \
    ! -name "*.eot" \
    ! -name "*.svg" \
    ! -name "*.zip" \
    ! -name "*.gz" \
    ! -name "*.war" \
    -exec sed "${SED_INPLACE[@]}" -e 's/cawl\([A-Z]\)/CAWL\1/g' {} +

# Pass 2: Java files - fix only inside quoted strings (bean name references
# and view/path constants). Two patterns:
#   "cawl[A-Z]  -> handles string-start:  "cawlDeliveryAddr..." -> "CAWLDeliveryAddr..."
#   /cawl[A-Z]  -> handles mid-path refs: "pages/.../cawlDeliveryAddr..." -> ".../CAWLDeliveryAddr..."
find . -type f -name "*.java" \
    -exec sed "${SED_INPLACE[@]}" \
        -e 's/"cawl\([A-Z]\)/"CAWL\1/g' \
        -e 's/\/cawl\([A-Z]\)/\/CAWL\1/g' {} +

echo "  Fixed CAWL acronym casing in config files and Java string literals."

# ------------------------------------------------------------------------------
# 6c. Drop self-referential deprecated property aliases
# ------------------------------------------------------------------------------
# The source plugin keeps backward-compatible aliases of the form
#   worldline.gopay.api.connectTimeout=${worldline.direct.api.connectTimeout}
# so that merchants upgrading from the pre-GoPay naming keep their overrides.
# Both halves collapse onto the same name in the CAWL variant (worldline->cawl
# and gopay->direct), which would leave a circular reference:
#   cawl.direct.api.connectTimeout=${cawl.direct.api.connectTimeout}
# The CAWL variant has no legacy merchants, so the alias is simply dropped and
# the remaining line (which carries the real default value) becomes canonical.
echo ""
echo "=== Step 5c: Removing self-referential property aliases ==="

find . -type f -name "*.properties" | while IFS= read -r pf; do
    tmp="${pf}.tmp$$"
    awk '''{
        if ($0 ~ /^[A-Za-z0-9_.]+=\$\{[A-Za-z0-9_.]+\}$/) {
            k = substr($0, 1, index($0, "=") - 1)
            v = substr($0, index($0, "=") + 1)
            if (v == "${" k "}") { print "  DROPPED: " $0 > "/dev/stderr"; next }
        }
        print
    }''' "$pf" > "$tmp" && mv "$tmp" "$pf"
done

echo "  Self-referential aliases removed."

# Pass 3: Rename files whose names contain cawl[A-Z] to CAWL[A-Z]
# e.g. cawlReplenishmentScheduleForm.tag -> CAWLReplenishmentScheduleForm.tag
# This ensures JSP tag/include references (fixed in pass 1) match actual file names.
find . -type f | while IFS= read -r file; do
    base="$(basename "$file")"
    newbase="$(echo "$base" | sed -e 's/cawl\([A-Z]\)/CAWL\1/g')"
    if [[ "$base" != "$newbase" ]]; then
        mv "$file" "$(dirname "$file")/$newbase"
        echo "  FILE: $base -> $newbase"
    fi
done

# ------------------------------------------------------------------------------
# 7. Swap SDK dependency
# ------------------------------------------------------------------------------
echo ""
echo "=== Step 6: SDK dependency swap ==="

# Find the core extension's external-dependencies.xml and lib/ directory
# (after renaming, the extension is now "cawlcore")
CORE_EXT_DIR=$(find . -maxdepth 1 -type d -name "cawlcore" | head -1)

if [[ -z "$CORE_EXT_DIR" ]]; then
    echo "  WARNING: Could not find cawlcore extension directory. SDK swap skipped."
elif [[ -n "$CAWL_SDK_GROUP_ID" && -n "$CAWL_SDK_ARTIFACT_ID" && -n "$CAWL_SDK_VERSION" ]]; then
    echo "  Updating SDK coordinates:"
    echo "    groupId:    $CAWL_SDK_GROUP_ID"
    echo "    artifactId: $CAWL_SDK_ARTIFACT_ID"
    echo "    version:    $CAWL_SDK_VERSION"

    DEPS_XML="$CORE_EXT_DIR/external-dependencies.xml"

    if [[ -f "$DEPS_XML" ]]; then
        # The generic text replacement already changed "worldline" references in
        # the POM. Now we do a precise replacement of the SDK dependency
        # coordinates to the exact CAWL values, regardless of what the generic
        # pass produced.

        # Replace the SDK groupId (whatever it is now after generic replacement)
        sed "${SED_INPLACE[@]}" \
            -e "s|<groupId>com\.[^<]*-solutions</groupId>|<groupId>${CAWL_SDK_GROUP_ID}</groupId>|" \
            "$DEPS_XML"

        # Replace the SDK artifactId
        sed "${SED_INPLACE[@]}" \
            -e "s|<artifactId>onlinepayments-sdk-java</artifactId>|<artifactId>${CAWL_SDK_ARTIFACT_ID}</artifactId>|" \
            "$DEPS_XML"

        # Replace the version property value
        sed "${SED_INPLACE[@]}" \
            -e "s|<cawl\.direct\.version>[^<]*</cawl\.direct\.version>|<cawl.direct.version>${CAWL_SDK_VERSION}</cawl.direct.version>|" \
            "$DEPS_XML"

        echo "  Updated: $DEPS_XML"
    else
        echo "  WARNING: $DEPS_XML not found."
    fi

    # Swap the .jar file in lib/
    LIB_DIR="$CORE_EXT_DIR/lib"
    if [[ -d "$LIB_DIR" ]]; then
        # Remove the original Worldline SDK jar (name may vary after renaming)
        OLD_JAR=$(find "$LIB_DIR" \( -name "onlinepayments-sdk-java-*.jar" -o -name "*payments-sdk*.jar" \) | head -1)
        KEEP_JAR=false
        if [[ -n "$OLD_JAR" && -z "$CAWL_SDK_JAR" \
              && "$CAWL_SDK_ARTIFACT_ID" == "onlinepayments-sdk-java" \
              && "$(basename "$OLD_JAR")" == "onlinepayments-sdk-java-${CAWL_SDK_VERSION}.jar" ]]; then
            # Same artifact and version as the source plugin: nothing to swap.
            echo "  Keeping shipped SDK jar: $OLD_JAR"
            KEEP_JAR=true
        elif [[ -n "$OLD_JAR" ]]; then
            echo "  Removing old SDK jar: $OLD_JAR"
            rm -f "$OLD_JAR"
        fi

        if [[ "$KEEP_JAR" == "true" ]]; then
            :
        elif [[ -n "$CAWL_SDK_JAR" && -f "$CAWL_SDK_JAR" ]]; then
            # Option B: Copy the provided local jar
            cp "$CAWL_SDK_JAR" "$LIB_DIR/"
            echo "  Copied new SDK jar: $CAWL_SDK_JAR -> $LIB_DIR/"
        elif command -v mvn >/dev/null 2>&1; then
            # Option A: Download via Maven
            echo "  Downloading SDK jar via Maven..."
            mvn dependency:copy \
                -Dartifact="${CAWL_SDK_GROUP_ID}:${CAWL_SDK_ARTIFACT_ID}:${CAWL_SDK_VERSION}" \
                -DoutputDirectory="$LIB_DIR" \
                -q 2>&1 && echo "  SDK jar downloaded to $LIB_DIR/" \
                || echo "  WARNING: Maven download failed. Place the jar manually in $LIB_DIR/"
        else
            echo "  WARNING: No local jar provided and Maven not available."
            echo "  Please manually place ${CAWL_SDK_ARTIFACT_ID}-${CAWL_SDK_VERSION}.jar in $LIB_DIR/"
        fi
    else
        echo "  WARNING: $LIB_DIR not found."
    fi
else
    echo "  SDK swap skipped (CAWL_SDK_GROUP_ID/ARTIFACT_ID/VERSION not set)."
    echo "  Restoring original Worldline SDK coordinates in external-dependencies.xml."

    # The generic text replacement corrupted the Maven groupId from
    # com.worldline-solutions to com.cawl-solutions. Restore the original
    # coordinates so the dependency still resolves against Maven Central.
    DEPS_XML="$CORE_EXT_DIR/external-dependencies.xml"
    if [[ -f "$DEPS_XML" ]]; then
        sed "${SED_INPLACE[@]}" \
            -e 's|<groupId>com\.cawl-solutions</groupId>|<groupId>com.worldline-solutions</groupId>|' \
            -e 's|<cawl\.direct\.version>|<worldline.gopay.version>|' \
            -e 's|</cawl\.direct\.version>|</worldline.gopay.version>|' \
            -e 's|\${cawl\.direct\.version}|${worldline.gopay.version}|' \
            "$DEPS_XML"
        echo "  Restored: $DEPS_XML"
    fi

    echo ""
    echo "  To use a CAWL-branded SDK, set environment variables before running:"
    echo "    export CAWL_SDK_GROUP_ID='com.cawl-solutions'"
    echo "    export CAWL_SDK_ARTIFACT_ID='cawl-payments-sdk-java'"
    echo "    export CAWL_SDK_VERSION='1.0.0'"
    echo "    export CAWL_SDK_JAR='/path/to/jar'   # optional, will use Maven if omitted"
fi

# ------------------------------------------------------------------------------
# 8. Post-processing verification
# ------------------------------------------------------------------------------
echo ""
echo "=== Step 7: Verification ==="

# The Maven groupId of the upstream SDK (com.worldline-solutions) is a
# required external coordinate, not a branding leak, so it is excluded.
remaining_files=$(grep -rl "worldline\|Worldline\|WORLDLINE\|gopay\|GoPay\|GOPAY" . \
    --include="*.java" \
    --include="*.xml" \
    --include="*.properties" \
    --include="*.impex" \
    --include="*.jsp" \
    --include="*.tag" \
    --include="*.js" \
    --include="*.css" \
    --include="*.less" \
    --include="*.json" \
    2>/dev/null | while IFS= read -r f; do
        if grep -v "com\.worldline-solutions" "$f" | grep -q "worldline\|Worldline\|WORLDLINE\|gopay\|GoPay\|GOPAY"; then
            echo "$f"
        fi
    done || true)

if [[ -n "$remaining_files" ]]; then
    echo "  WARNING: The following files still contain 'worldline' or 'gopay' references:"
    echo "$remaining_files" | while IFS= read -r f; do
        echo "    $f"
        grep -v "com\.worldline-solutions" "$f" | grep -n "worldline\|Worldline\|WORLDLINE\|gopay\|GoPay\|GOPAY" | head -5 | while IFS= read -r line; do
            echo "      $line"
        done
    done
    echo ""
    echo "  These may be false positives (e.g. external SDK references) or may"
    echo "  need manual attention or handling via the overwrites mechanism."
else
    echo "  SUCCESS: No remaining 'worldline' or 'gopay' references found in source files."
fi

remaining_worldline_files=$(find . \( -name "*worldline*" -o -name "*Worldline*" -o -name "*gopay*" -o -name "*GoPay*" \) 2>/dev/null || true)
if [[ -n "$remaining_worldline_files" ]]; then
    echo ""
    echo "  WARNING: Files/dirs still containing 'worldline' or 'gopay' in their name:"
    echo "$remaining_worldline_files" | while IFS= read -r f; do echo "    $f"; done
else
    echo "  SUCCESS: No files or directories with 'worldline' or 'gopay' in their name."
fi

# ------------------------------------------------------------------------------
# 9. Apply file overwrites (if overwrites directory exists)
# ------------------------------------------------------------------------------
cd ..

OVERWRITES_DIR="$(dirname "$0")/overwrites"
if [[ -d "$OVERWRITES_DIR" ]]; then
    echo ""
    echo "=== Step 8: Applying file overwrites ==="
    rsync -aI "$OVERWRITES_DIR"/ "$DEST_DIR"/
    echo "  Overwrites applied from $OVERWRITES_DIR"
else
    echo ""
    echo "=== Step 8: No overwrites directory found at $OVERWRITES_DIR - skipping ==="
fi

# ------------------------------------------------------------------------------
# 10. Package artifacts (optional)
# ------------------------------------------------------------------------------
echo ""
echo "=== Step 9: Packaging ==="
ARCHIVE_NAME="cawl_hybris_plugin.zip"
zip -qr "$ARCHIVE_NAME" "$DEST_DIR"
ls -lh "$ARCHIVE_NAME"

echo ""
echo "Done! Output in: $DEST_DIR"
echo "Archive: $ARCHIVE_NAME"
