# -----------------------------------------------------------------------
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
# -----------------------------------------------------------------------

worldlinegopaywebhook.webroot=/worldlinegopaywebhook_junit
worldlinegopaywebhook.security.config=config/test-security-spring.xml
worldlinegopaywebhook.ehcache.location=worldlinegopaywebhook/cache/junit_ehcache.xml